'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OPT.OrionP.WinCom.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _Cerrar.
        '''</summary>
        Friend ReadOnly Property CerrarBtn() As String
            Get
                Return ResourceManager.GetString("CerrarBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  de .
        '''</summary>
        Friend ReadOnly Property De() As String
            Get
                Return ResourceManager.GetString("De", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a : .
        '''</summary>
        Friend ReadOnly Property DosPuntosEspacio() As String
            Get
                Return ResourceManager.GetString("DosPuntosEspacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a - .
        '''</summary>
        Friend ReadOnly Property GuionSeparador() As String
            Get
                Return ResourceManager.GetString("GuionSeparador", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importar Objeto .
        '''</summary>
        Friend ReadOnly Property ImportarObjeto() As String
            Get
                Return ResourceManager.GetString("ImportarObjeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DEFINICION BASE DE DATOS.
        '''</summary>
        Friend ReadOnly Property NomBasDat() As String
            Get
                Return ResourceManager.GetString("NomBasDat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CAMBIO CONTRASEÑA.
        '''</summary>
        Friend ReadOnly Property NomCamCon() As String
            Get
                Return ResourceManager.GetString("NomCamCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONSULTAS SQL.
        '''</summary>
        Friend ReadOnly Property NomConSql() As String
            Get
                Return ResourceManager.GetString("NomConSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a COPIA DE SEGURIDAD.
        '''</summary>
        Friend ReadOnly Property NomCopSeg() As String
            Get
                Return ResourceManager.GetString("NomCopSeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IMPORTACIÓN.
        '''</summary>
        Friend ReadOnly Property NomImp() As String
            Get
                Return ResourceManager.GetString("NomImp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REGISTRO ACCIONES EN LA APLICACION.
        '''</summary>
        Friend ReadOnly Property NomLogApp() As String
            Get
                Return ResourceManager.GetString("NomLogApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TERCEROS.
        '''</summary>
        Friend ReadOnly Property NomTercer() As String
            Get
                Return ResourceManager.GetString("NomTercer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a UBICACION.
        '''</summary>
        Friend ReadOnly Property NomUbica() As String
            Get
                Return ResourceManager.GetString("NomUbica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registros Procesados: .
        '''</summary>
        Friend ReadOnly Property RegProcesados() As String
            Get
                Return ResourceManager.GetString("RegProcesados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tercero.
        '''</summary>
        Friend ReadOnly Property Tercero() As String
            Get
                Return ResourceManager.GetString("Tercero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Imagen(.jpg)|*.jpg.
        '''</summary>
        Friend ReadOnly Property TipoArchivoImagen() As String
            Get
                Return ResourceManager.GetString("TipoArchivoImagen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Archivo Excel (*.xls, *.xlsx)|*.xls;*.xlsx|Archivo Access (*.mdb)|*.mdb|Todos los archivos (*.*)|*.*.
        '''</summary>
        Friend ReadOnly Property TiposArchivosOrigen() As String
            Get
                Return ResourceManager.GetString("TiposArchivosOrigen", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
