'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OPT.OrionP.OriWin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre la Ayuda de Panorama..
        '''</summary>
        Friend ReadOnly Property AbreAyuda() As String
            Get
                Return ResourceManager.GetString("AbreAyuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAyuda.
        '''</summary>
        Friend ReadOnly Property AbreAyudaCmd() As String
            Get
                Return ResourceManager.GetString("AbreAyudaCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre el Bloc de Notas de Windows..
        '''</summary>
        Friend ReadOnly Property AbreBloc() As String
            Get
                Return ResourceManager.GetString("AbreBloc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdNotas.
        '''</summary>
        Friend ReadOnly Property AbreBlocCmd() As String
            Get
                Return ResourceManager.GetString("AbreBlocCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre la Calculadora de Windows..
        '''</summary>
        Friend ReadOnly Property AbreCalc() As String
            Get
                Return ResourceManager.GetString("AbreCalc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCalculadora.
        '''</summary>
        Friend ReadOnly Property AbreCalcCmd() As String
            Get
                Return ResourceManager.GetString("AbreCalcCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre el Calendario de Windows..
        '''</summary>
        Friend ReadOnly Property AbreCalendario() As String
            Get
                Return ResourceManager.GetString("AbreCalendario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCalendario.
        '''</summary>
        Friend ReadOnly Property AbreCalendarioCmd() As String
            Get
                Return ResourceManager.GetString("AbreCalendarioCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre los Mensajes de Panorama..
        '''</summary>
        Friend ReadOnly Property AbreMens() As String
            Get
                Return ResourceManager.GetString("AbreMens", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdMensajes.
        '''</summary>
        Friend ReadOnly Property AbreMensCmd() As String
            Get
                Return ResourceManager.GetString("AbreMensCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Acepta los cambios en la Ventana..
        '''</summary>
        Friend ReadOnly Property AceptaCam() As String
            Get
                Return ResourceManager.GetString("AceptaCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAceptar.
        '''</summary>
        Friend ReadOnly Property AceptaCamCmd() As String
            Get
                Return ResourceManager.GetString("AceptaCamCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ADVERTENCIA: .
        '''</summary>
        Friend ReadOnly Property Advertencia() As String
            Get
                Return ResourceManager.GetString("Advertencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAnular.
        '''</summary>
        Friend ReadOnly Property AnuCmd() As String
            Get
                Return ResourceManager.GetString("AnuCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anular un Objeto.
        '''</summary>
        Friend ReadOnly Property AnuObj() As String
            Get
                Return ResourceManager.GetString("AnuObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Calendario.
        '''</summary>
        Friend ReadOnly Property Calendario() As String
            Get
                Return ResourceManager.GetString("Calendario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INFORMACION: Aún hay campos requeridos por satisfacer!.
        '''</summary>
        Friend ReadOnly Property CamposSinSatisfacer() As String
            Get
                Return ResourceManager.GetString("CamposSinSatisfacer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancela los cambios en la Ventana..
        '''</summary>
        Friend ReadOnly Property CancelaCam() As String
            Get
                Return ResourceManager.GetString("CancelaCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCancelar.
        '''</summary>
        Friend ReadOnly Property CancelaCamCmd() As String
            Get
                Return ResourceManager.GetString("CancelaCamCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _Cancelar.
        '''</summary>
        Friend ReadOnly Property Cancelar() As String
            Get
                Return ResourceManager.GetString("Cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _Cerrar.
        '''</summary>
        Friend ReadOnly Property CerrarBtn() As String
            Get
                Return ResourceManager.GetString("CerrarBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cierra la Ventana actual..
        '''</summary>
        Friend ReadOnly Property CierraWin() As String
            Get
                Return ResourceManager.GetString("CierraWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCerrar.
        '''</summary>
        Friend ReadOnly Property CierraWinCmd() As String
            Get
                Return ResourceManager.GetString("CierraWinCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCrear.
        '''</summary>
        Friend ReadOnly Property CrearCmd() As String
            Get
                Return ResourceManager.GetString("CrearCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Crear un Objeto.
        '''</summary>
        Friend ReadOnly Property CrearObj() As String
            Get
                Return ResourceManager.GetString("CrearObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DATO INVALIDO: .
        '''</summary>
        Friend ReadOnly Property DatInv() As String
            Get
                Return ResourceManager.GetString("DatInv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ERROR: .
        '''</summary>
        Friend ReadOnly Property ErrorStr() As String
            Get
                Return ResourceManager.GetString("ErrorStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Consultando.
        '''</summary>
        Friend ReadOnly Property EstConsultando() As String
            Get
                Return ResourceManager.GetString("EstConsultando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Creando.
        '''</summary>
        Friend ReadOnly Property EstCreando() As String
            Get
                Return ResourceManager.GetString("EstCreando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificando.
        '''</summary>
        Friend ReadOnly Property EstModificando() As String
            Get
                Return ResourceManager.GetString("EstModificando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a EXCEPCION: .
        '''</summary>
        Friend ReadOnly Property Excep() As String
            Get
                Return ResourceManager.GetString("Excep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FALTA: .
        '''</summary>
        Friend ReadOnly Property Falta() As String
            Get
                Return ResourceManager.GetString("Falta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdGuardar.
        '''</summary>
        Friend ReadOnly Property GuaCmd() As String
            Get
                Return ResourceManager.GetString("GuaCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guardar los cambios en el Objeto.
        '''</summary>
        Friend ReadOnly Property GuaObj() As String
            Get
                Return ResourceManager.GetString("GuaObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INFORMACION: .
        '''</summary>
        Friend ReadOnly Property Informacion() As String
            Get
                Return ResourceManager.GetString("Informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlAnterior.
        '''</summary>
        Friend ReadOnly Property IrAntCmd() As String
            Get
                Return ResourceManager.GetString("IrAntCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Anterior.
        '''</summary>
        Friend ReadOnly Property IrAntObj() As String
            Get
                Return ResourceManager.GetString("IrAntObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdBuscar.
        '''</summary>
        Friend ReadOnly Property IrBusCmd() As String
            Get
                Return ResourceManager.GetString("IrBusCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Busca un Objeto.
        '''</summary>
        Friend ReadOnly Property IrBusObj() As String
            Get
                Return ResourceManager.GetString("IrBusObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlPrimero.
        '''</summary>
        Friend ReadOnly Property IrPriCmd() As String
            Get
                Return ResourceManager.GetString("IrPriCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Primero.
        '''</summary>
        Friend ReadOnly Property IrPriObj() As String
            Get
                Return ResourceManager.GetString("IrPriObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlSiguiente.
        '''</summary>
        Friend ReadOnly Property IrSigCmd() As String
            Get
                Return ResourceManager.GetString("IrSigCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Siguiente.
        '''</summary>
        Friend ReadOnly Property IrSigObj() As String
            Get
                Return ResourceManager.GetString("IrSigObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlUltimo.
        '''</summary>
        Friend ReadOnly Property IrUltCmd() As String
            Get
                Return ResourceManager.GetString("IrUltCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Ultimo.
        '''</summary>
        Friend ReadOnly Property IrUltObj() As String
            Get
                Return ResourceManager.GetString("IrUltObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdModificar.
        '''</summary>
        Friend ReadOnly Property ModCmd() As String
            Get
                Return ResourceManager.GetString("ModCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar un Objeto.
        '''</summary>
        Friend ReadOnly Property ModObj() As String
            Get
                Return ResourceManager.GetString("ModObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CAMBIO DE CONTRASEÑA.
        '''</summary>
        Friend ReadOnly Property NomCamCon() As String
            Get
                Return ResourceManager.GetString("NomCamCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdRefrescar.
        '''</summary>
        Friend ReadOnly Property RefCmd() As String
            Get
                Return ResourceManager.GetString("RefCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Refrescar un Objeto.
        '''</summary>
        Friend ReadOnly Property RefObj() As String
            Get
                Return ResourceManager.GetString("RefObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sale de la Aplicación..
        '''</summary>
        Friend ReadOnly Property SaleApp() As String
            Get
                Return ResourceManager.GetString("SaleApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdSalirApp.
        '''</summary>
        Friend ReadOnly Property SaleAppCmd() As String
            Get
                Return ResourceManager.GetString("SaleAppCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdSuprimir.
        '''</summary>
        Friend ReadOnly Property SupCmd() As String
            Get
                Return ResourceManager.GetString("SupCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Suprimir un Objeto.
        '''</summary>
        Friend ReadOnly Property SupObj() As String
            Get
                Return ResourceManager.GetString("SupObj", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
